#!/usr/bin/env python3
"""Convert Nemotron-Cascade-2-SFT-Data DeepSeek partitions -> hive parquet.

Keeps ONLY records whose generator is in {DeepSeek-V3.2, DeepSeek-V3.2-Speciale}.
Records generated by GPT-OSS-120B and DeepSeek-R1-0528 are dropped (counted).

Layout:
  parquet/domain=<d>/generator=<g>/part-NNNN.parquet

Schema: domain/source/generator as native string columns; messages as a compact
JSON string. Each record is {domain, source, generator, messages:[{role,content}]}.
messages may embed tool interaction as INLINE special tokens (e.g. <|im_start|>,
<tool_response>, <think>) -- there is no structured tool_calls field, so the whole
messages list is preserved byte-exact via JSON string (ensure_ascii=False). The
training loader is responsible for parsing the inline tool format.

Strategy: split each input file into N byte ranges, one worker per range. Each
worker aligns to a line boundary (discarding the partial leading line; the next
worker's range starts there) and processes whole lines whose start offset falls
within [start, end) -- lossless, no overlap. Rows are bucketed into
(domain, generator) partitions and flushed in batches. Fail-loud on any
unexpected field/value.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from multiprocessing import Pool

import pyarrow as pa
import pyarrow.parquet as pq

SCHEMA = pa.schema([
    ("domain", pa.string()),
    ("source", pa.string()),
    ("generator", pa.string()),
    ("messages", pa.string()),
])

KEEP = {"DeepSeek-V3.2", "DeepSeek-V3.2-Speciale"}
DOMAINS = {"math_notool", "math_tool", "math_proof", "swe_agentless", "terminal_agent"}
BATCH_ROWS = 1000

INPUTS = [
    "math/math_notool.jsonl",
    "math/math_tool.jsonl",
    "math/math_proof.jsonl",
    "swe/swe_agentless.jsonl",
    "terminal_agent/terminal_agent.jsonl",
]


def partition_dir(out_root: str, domain: str, generator: str) -> str:
    return os.path.join(out_root, f"domain={domain}", f"generator={generator}")


def worker(args):
    gid, path, start, end, out_root = args
    writers: dict[tuple, pq.ParquetWriter] = {}
    buffers: dict[tuple, dict] = {}
    counts: dict[tuple, int] = {}
    dropped = 0
    n_lines = 0

    def new_buffer():
        return {c: [] for c in SCHEMA.names}

    def flush(key):
        buf = buffers[key]
        if not buf["domain"]:
            return
        batch = pa.record_batch(
            [pa.array(buf[c], type=SCHEMA.field(c).type) for c in SCHEMA.names],
            schema=SCHEMA,
        )
        if key not in writers:
            d = partition_dir(out_root, *key)
            os.makedirs(d, exist_ok=True)
            fp = os.path.join(d, f"part-{gid:04d}.parquet")
            writers[key] = pq.ParquetWriter(
                fp, SCHEMA, compression="zstd", compression_level=3)
        writers[key].write_batch(batch)
        buffers[key] = new_buffer()

    with open(path, "rb") as f:
        f.seek(start)
        if start > 0:
            f.readline()  # discard partial line; previous worker owns it
        while f.tell() < end:
            raw = f.readline()
            if not raw:
                break
            n_lines += 1
            r = json.loads(raw)
            dom = r["domain"]
            gen = r["generator"]
            if dom not in DOMAINS:
                raise ValueError(f"unexpected domain {dom!r} in {path}")
            if gen not in KEEP:
                dropped += 1
                continue
            msgs = r["messages"]
            for m in msgs:
                if set(m.keys()) != {"role", "content"}:
                    raise ValueError(
                        f"unexpected message keys {sorted(m.keys())} in {path}")
                if not isinstance(m["content"], str):
                    raise ValueError(f"non-str content in {path}")
            key = (dom, gen)
            if key not in buffers:
                buffers[key] = new_buffer()
                counts[key] = 0
            b = buffers[key]
            b["domain"].append(dom)
            b["source"].append(r["source"])
            b["generator"].append(gen)
            b["messages"].append(
                json.dumps(msgs, ensure_ascii=False, separators=(",", ":")))
            counts[key] += 1
            if len(b["domain"]) >= BATCH_ROWS:
                flush(key)

    for key in list(buffers):
        flush(key)
    for w in writers.values():
        w.close()
    return {
        "path": path,
        "n_lines": n_lines,
        "dropped": dropped,
        "counts": {f"{k[0]}|{k[1]}": v for k, v in counts.items()},
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True, help="dataset dir (contains math/, swe/, ...)")
    ap.add_argument("--out", required=True)
    ap.add_argument("--workers", type=int, default=os.cpu_count())
    args = ap.parse_args()

    if os.path.exists(args.out) and os.listdir(args.out):
        sys.exit(f"output dir not empty: {args.out} (refusing to mix)")
    os.makedirs(args.out, exist_ok=True)

    tasks = []
    gid = 0
    total_in = 0
    for rel in INPUTS:
        path = os.path.join(args.root, rel)
        size = os.path.getsize(path)
        total_in += size
        step = size // args.workers
        for i in range(args.workers):
            s = i * step
            e = size if i == args.workers - 1 else (i + 1) * step
            tasks.append((gid, path, s, e, args.out))
            gid += 1

    print(f"inputs={len(INPUTS)} total={total_in/1e9:.1f}GB "
          f"workers={args.workers} tasks={len(tasks)}", flush=True)
    with Pool(args.workers) as pool:
        results = pool.map(worker, tasks)

    total_lines = sum(r["n_lines"] for r in results)
    total_dropped = sum(r["dropped"] for r in results)
    part_counts: dict[str, int] = {}
    for r in results:
        for k, v in r["counts"].items():
            part_counts[k] = part_counts.get(k, 0) + v

    kept = sum(part_counts.values())
    print(f"\nTOTAL lines read: {total_lines}")
    print(f"kept (DeepSeek): {kept}   dropped (non-DeepSeek): {total_dropped}")
    assert kept + total_dropped == total_lines, "kept+dropped != total lines"
    print("per-partition counts (domain|generator):")
    for k in sorted(part_counts):
        print(f"  {k}: {part_counts[k]}")


if __name__ == "__main__":
    main()
